---
- hosts: localhost
  become: true
  
  tasks:
  - name: Run apt update if not run in last hour
    apt:
      update_cache: yes
      cache_valid_time: 3600
    
  - name: Install packages
    apt: 
      name:
        - git
        - yakuake
        - htop
        - zsh
        
        - python3
        # Dev C headers for compiling such as for lxml
        - python3-dev
   
        # Installed already on Linux Lite but included for completeness
        - curl
        - ssh
        - scp
        - rsync
      state: latest  

  - name: Install Ruby
    apt:
      name:
        - ruby
        - ruby-dev
        - make
  
  - name: Install gems with proper $PATH
    gem:
      name: bundler
      user_install: yes

  - name: Update all packages to the latest version (not just the ones named in playbook)
    apt:
      upgrade: dist

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
