---
- hosts: localhost
  become: true
  tasks:
  - name: Install system updates for ubuntu systems
    apt: upgrade=dist update_cache=yes
    when: ansible_distribution == "Ubuntu"
    
  - name: Install packages
    apt: name=['htop', 'yakuake']
