---
- hosts: localhost
  become: true
  
  tasks:
  - name: Run apt update if not run in last hour
    apt:
      update_cache: yes
      cache_valid_time: 3600
 
  - debug:
      msg: Starting installs / updates
    
  - name: Install / update packages
    apt: 
      name:
        - git
        - yakuake
        - zsh
        - vim
        - wget
   
        # Installed already on Linux Lite but included for completeness
        - curl
        - ssh
        - rsync
        - htop
        - nano
      state: latest  

  - name: Install Python
    apt:
      name:
       - python3
       # C headers for compiling extensions - needed for lxml
       - python3-dev

  - include_role:
      name: geerlingguy.nodejs
    vars:
      nodejs_version: "14.x"

  - name: Install Ruby
    apt:
      name:
        - ruby
        - ruby-dev
        - make
  
  - name: Install gems with proper $PATH
    gem:
      name: bundler
      user_install: yes

  # This may be dangerous for Python envs
  - name: Update all packages to the latest version (not just the ones named in playbook)
    apt:
      # Uses apt-get not aptitude
      upgrade: dist
  
  - debug:
      msg: Starting clean-up steps
  
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Show versions for important packages
    shell: |
      python3 -V
      node -v
      npm -v
      ruby --version
      bundler --version
      zsh --version
      git --version
    register: versions_output
  - debug:
      msg: "{{ versions_output.stdout }}"   
